name: Build iOS Framework

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    name: Build iOS Framework
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java (Kotlin/Gradle requires a JDK)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Build the iOS Framework
      - name: Build iOS binaries
        run: ./gradlew :shared:assemble

      # Step 6: Upload build artifacts (Optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-framework
          path: shared/build/bin/
