on:
  release:
    types: [ created ]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish
        run: |
          cd ${GITHUB_WORKSPACE}
          chmod +x ./gradlew
          ./gradlew check publish --no-configure-on-demand --no-daemon
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
          GitHubPackagesUsername: ${{ github.actor }}
          GitHubPackagesPassword: ${{ github.token }}